### ISSUE TITLE
Bots difficulty is insane even on easy

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#11]
Currently the bots in DM and enemies in Survival/Coop are very difficult. Compare them with the original Nexuiz or Xonotic.
Please optimize their difficulty.

**Comment by kasymovga** [comment]
"Easiest" difficulty will be added in next updates.

**Comment by YevheniiPokhvalii** [comment]
I see. Thanks.

**Comment by YevheniiPokhvalii** [comment]
Have you tried `Level 17` (instagib) on easy? I barely passed it. It feels more like hard not even normal. The bots are too precise.

**Comment by kasymovga** [comment]
>Have you tried Level 17 (instagib) on easy

Completed level 17 on easy on first attempt just now. But it's feels too difficult on medium and higher.
Probably will decrease bot skill just for this level.

**Comment by YevheniiPokhvalii** [comment]
> > Have you tried Level 17 (instagib) on easy
> 
> Completed level 17 on easy on first attempt just now. But it's feels too difficult on medium and higher. Probably will decrease bot skill just for this level.

Level 29 is also a bit difficult.

**Comment by kasymovga** [comment]
>survival, campaign, single player demo are insanely difficult in a solo

it's was never hard on easy and now you have easiest. "best coop" server have hard difficulty and lot of players with really low skill level don't have problem with it at all.

>tried to play DM with bots on the Advanced skill and the problem is - they are too accurate, it feels much more difficult than the medium skill should.

overall aim scale was decreased in last update. if you still think that advanced skill bots is too strong then stop play it in advanced mode.

**Comment by YevheniiPokhvalii** [comment]
> > survival, campaign, single player demo are insanely difficult in a solo
> 
> it's was never hard on easy and now you have easiest. "best coop" server have hard difficulty and lot of players with really low skill level don't have problem with it at all.
> 
> > tried to play DM with bots on the Advanced skill and the problem is - they are too accurate, it feels much more difficult than the medium skill should.
> 
> overall aim scale was decreased in last update. if you still think that advanced skill bots is too strong then stop play it in advanced mode.

Well, it's just my opinion based on experience with other games. Advanced skill in Rexuiz feels like Masterful, or Inhuman skill in Unreal Tournament 99 and UT bots are considered pretty smart.

> survival, campaign, single player demo are insanely difficult in a solo
Yep, I'm saying about a solo not multiplayer. I understand that in MP you play with a team and that is a bit easier (I tried it by the way and have no complaints). In a solo it is almost unplayable right now especially the more you progress. Please check it from your side.

Also, please try Level 29. It's almost the pain as level 17 was.

**Comment by kasymovga** [comment]
>Level 29

Completed with first attempt at hard difficulty.

**Comment by YevheniiPokhvalii** [comment]
> > Level 29
> 
> Completed at first attempt on hard difficulty.

Ok, I tested this rocket arena on Easy and Hard and I'd say that it feels almost the same. Just a subtle difference in intensity but still hard.
