### ISSUE TITLE
Set start delay 0 by default

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#12]
It's very annoying to create an offline match with the "Start delay 15 sec" by default. If I change it to "0", it's always resetting while restarting the game.
Please make it "0" by default, or save it after quitting the game.
By the way, it's "0" by default in Nexuiz.

**Comment by kasymovga** [comment]
this settings become saveable in next update.
for now you can use console command: `seta g_start_delay 0` as workaround.

**Comment by YevheniiPokhvalii** [comment]
> this settings become saveable in next update. for now you can use console command: `seta g_start_delay 0` as workaround.

Thank you. Maybe set it as "0" be default in the next update as well? New players does not know where that setting is located and it's very annoying to start with that 15sec delay.

**Comment by kasymovga** [comment]
i think i will add additional cvar with delay for non-public games with 0 by default.
