### ISSUE TITLE
HUD background is not visible

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#13]
Hood background setting does not work. The hood frame is not visible no matter how I configure it via GUI. It's bad for team matches. Sometimes it's tricky to understand what team you are at despite the weapon colors. This is especially problematic in a singleplayer.
Here are screenshots from Rexuiz and Nexuiz  for comparison:
Rexuiz:
![rexuiz20230319003743-00](https://user-images.githubusercontent.com/68227075/226143822-8436170f-3a06-4311-a706-2091676201aa.jpg)
Nexuiz:
![nexuiz000000](https://user-images.githubusercontent.com/68227075/226143864-b36aede8-c9a7-4a93-b762-9b2a3d4fef59.jpg)

**Comment by kasymovga** [comment]
this "hood" was removed intentionally, main reason that rexuiz hud elements don't have fixed location on screen.
but you can try "RM HUD" (in game: esc -> game settings -> hud settings -> use RM hud -> always, note that it will download small package from internet).
score indicator (right-down corner) actually have team colorizing, but probably it must be more noticeable. i think i will do something with this later.

**Comment by YevheniiPokhvalii** [comment]
> this "hood" was removed intentionally, main reason that rexuiz hud elements don't have fixed location on screen. but you can try "RM HUD" (in game: esc -> game settings -> hud settings -> use RM hud -> always, note that it will download small package from internet). score indicator (right-down corner) actually have team colorizing, but probably it must be more noticeable. i think i will do something with this later.

The HUD background setting does not respond. Probably, it may be necessary to change or remove it?
Having the HUD setting in two places is confusing.

![rexuiz20230319112529-00](https://user-images.githubusercontent.com/68227075/226165938-4ee10d09-c7c0-4ea5-b8b6-f32953f2d597.jpg)

**Comment by kasymovga** [comment]
![devel20230319174220-00](https://user-images.githubusercontent.com/9973821/226175964-78135f84-31ed-4de8-98b4-d3bdd495b32c.jpg)
need some cleaning and testing, but i think it will be something like this.

**Comment by kasymovga** [comment]
added in latest update
`cvarlist sbar_*_background`
0 not show, 1 in teamplay, 2 always.
this is in-game cvars, you need launch local game before edit these cvars.
for now there is no gui to adjust this settings, probably will be added later.

**Comment by YevheniiPokhvalii** [comment]
> added in latest update `cvarlist sbar_*_background` 0 not show, 1 in teamplay, 2 always. this is in-game cvars, you need launch local game before edit these cvars. for now there is no gui to adjust this settings, probably will be added later.

It's definitely better now. Thank you. But I think the colors are too weak. In dark places on a map, I still barely see what team I'm on. Please make the colors stronger or add an option to modify them in the menu in the future.
Here is the comparison between Nexuiz and Rexuiz:
Nexuiz:
![nexuiz000009](https://user-images.githubusercontent.com/68227075/227385466-eaad79ca-f466-4910-9420-5b8927a7f9cf.jpg)

Rexuiz:
![rexuiz20230324010914-00](https://user-images.githubusercontent.com/68227075/227385533-7b9931b9-eb18-4300-8956-dccca6ec8e86.jpg)

**Comment by kasymovga** [comment]
you can do it by yourself.
```
sbar_alpha_bg 1
sbar_timer_background 1
sbar_ammo_background 1
```

**Comment by YevheniiPokhvalii** [comment]
> you can do it by yourself.
> 
> ```
> sbar_alpha_bg 1
> sbar_timer_background 1
> sbar_ammo_background 1
> ```

Cool. Thanks. Hope to see these settings in the menu in some future update.

**Comment by kasymovga** [comment]
you can override gfx/hud/sb_ammobg.tga file in local folder
OR
you can enable RM HUD which have several skin modes (but without position customization, only 2 hard-coded choices).

also i agree that these stripes is actually don't looks great and probably i will replace this file in some next updates. let's hope the replacement will be at least not worse.

**Comment by YevheniiPokhvalii** [comment]
I fixed that image. Will send you.

**Comment by kasymovga** [comment]
can be done via alias:
`alias sbar_all_background "sbar_timer_background $1; sbar_score_background $1; ..."`
i think i will add later.
