### ISSUE TITLE
Random team switching in singleplayer 

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#14]
I understand that singleplayer is rarely played in this game but still.
In Rexuiz, each new match in singleplayer I start on a team with a random color. So, each new match - new color till the end of the match.
While this feature seems good on paper, it becomes very confusing what team you are fighting for, especially when there are several teams in keyhunt.
I also submitted another connected issue with the HUD that does not clearly states your team color.
Even in major games like Unreal Tournament you always play for one team in a singleplayer and it can be changed in the settings and the game itself does not change the team color randomly for you each match.
Nexuiz does not have that problem and you are always on a blue team side.

P.S. Some observations: when there are several teams like in domination and keyhunt Nexuiz also puts you to a random team.

**Comment by kasymovga** [comment]
It's really bad idea teach players that on of team better than other. So this behavior will left unchanged.
