### ISSUE TITLE
Are docs planned? How to play tuba?

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#16]
Nexuiz has a couple of interesting files in its docs folder:

![tuba](https://user-images.githubusercontent.com/68227075/226169735-8a27463c-53d7-4f9d-95b2-a0ecbdb0ee5d.png)

Rexuiz keeps it secret, though.

In game tube tutorial as well maybe? It could be fun.

**Comment by kasymovga** [comment]
Tuba works exactly same way as in Nexuiz.
Currently nobody want to write documentation, so there is no any. I assume that you mean some one big information collection about everything.

**Comment by YevheniiPokhvalii** [comment]
> Tuba works exactly same way as in Nexuiz. Currently nobody want to write documentation, so there is no any. I assume that you mean some one big information collection about everything.

There are a couple of files in the Nexuiz docs: tuba.png and tuba.svg. You can put them as an easter egg to the Rexuiz docs.
