### ISSUE TITLE
tga pictures converted to jpg

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#19]
I can see that most Nexuiz gfx, textures, etc. are in .tga format and some of them are in .jpg in Rexuiz. Was there a reason for that?
.jpg has a lower quality and it seems that some .jpg elements do not work in Rexuiz.

**Comment by kasymovga** [comment]
just for smaller size.

>some .jpg elements do not work in Rexuiz.
provide example, because i don't know any jpg related issues.

**Comment by YevheniiPokhvalii** [comment]
> just for smaller size.
> 
> > some .jpg elements do not work in Rexuiz.
> 
> provide example please, because i don't know any jpg related issues.

I am not sure but probably it's the thing connected with the missing radar. I might be wrong.

**Comment by kasymovga** [comment]
Radar was just removed from hud because it's mostly useless and also have impact to performance (at least it was noticeable years ago).
Note that mini map is still available (it's actually same thing as radar, just with fixed position) by pressing "m" button.
So, there is no any relation with image formats.

**Comment by YevheniiPokhvalii** [comment]
> Radar was just removed from hud because it's mostly useless and also have impact to performance (at least it was noticeable years ago). Note that mini map is still available (it's actually same thing as radar, just with fixed position) by pressing "m" button. So, there is no any relation with image formats.

minimap is not the same and it take half of the screen.
