### ISSUE TITLE
game speed option is missing

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#20]
This option seems strange in Nexuiz but it actually may help to test some items respawning, huge maps in Rexuiz when speeding up.
Or slowing down may help to check speed acceleration, particle effects etc.

**Comment by kasymovga** [comment]
```
g_slowmo 0.5
rereadcvars
```
note, you need rereadcvars to apply new value without restarting.

**Comment by kasymovga** [comment]
also in demos you need just `slowmo 0.5`

**Comment by YevheniiPokhvalii** [comment]
> ```
> g_slowmo 0.5
> rereadcvars
> ```
> 
> note, you need rereadcvars to apply new value without restarting.

Cool, so it'll only remain as a console feature. No plans to add it back to GUI?

**Comment by kasymovga** [comment]
No, this things more like for debugging, no reason to add this to GUI.

**Comment by YevheniiPokhvalii** [comment]
> No, this things more like for debugging, no reason to add this to GUI.

I see. I am asking because Nexuiz has it in the menu settings.
![nexuiz000008](https://user-images.githubusercontent.com/68227075/226455909-09e48afd-33f9-485c-8eac-e71a8104acdb.jpg)
