### ISSUE TITLE
Opportunity to switch between design of shown pressed keys

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#22]
It's a trivial request. 
Add an opportunity to switch between design of the pressed buttons. Make it customizable through the menu:
Xonotic like:
![image](https://user-images.githubusercontent.com/68227075/226214644-5dbf8e79-7817-4330-8403-22e9bfceb349.png)
Nexuiz like:
![image](https://user-images.githubusercontent.com/68227075/226214658-0e998be7-b47d-42a6-a9d7-dc42fadf16e6.png)

**Comment by kasymovga** [comment]
will be available on next update

**Comment by kasymovga** [comment]
settings -> interface -> "Use old key indicator"
