### ISSUE TITLE
Opportunity to switch between design of accelerometer

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#23]
Xonotic has a pretty neat accelerometer. I'd be nice to have the opportunity to switch between accelerometer designs.

![image](https://user-images.githubusercontent.com/68227075/226214958-70bbf5b1-e993-4630-92e0-4bbc5c22ed24.png)

**Comment by kasymovga** [comment]
i don't understand what exactly you want, but i add couple cvars:
```
cvarlist cl_showaccel*
cvarlist cl_showspeed*
```

**Comment by YevheniiPokhvalii** [comment]
> i don't understand what exactly you want, but i added couple cvars:
> 
> ```
> cvarlist cl_showaccel*
> cvarlist cl_showspeed*
> ```

I mean that the original Nexuiz/Rexuiz accelerometer is fat and ugly and takes a .huge portion of the screen.

**Comment by kasymovga** [comment]
`cl_showacceleration_width` and `cl_showacceleration_size`.

**Comment by YevheniiPokhvalii** [comment]
> cl_showacceleration_width

Is there a accelerometer snapzone customization?
![image](https://user-images.githubusercontent.com/68227075/228681661-4b21abe4-9315-4406-a7b3-fb86c2556968.png)
