### ISSUE TITLE
Remove 5 second delay after 'kill' and spectate command

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#24]
Xonotic or Quake 3 defrag do not have any delays when using "kill" or spectate. That parameter should be "0" be default.

**Comment by kasymovga** [comment]
this is not should be 0, because it can be abused in lot of circumstances.
this is 0 when it really needed (cts).

**Comment by YevheniiPokhvalii** [comment]
> this is not should be 0, because it can be abused in lot of circumstances. this is 0 when it really needed (cts).

Ok, It should be "0" in the Rece mod as well in that case.
How to set it to "0" from my side?

**Comment by kasymovga** [comment]
`g_balance_kill_delay 0`
probably will be set to 0 in race too.

**Comment by YevheniiPokhvalii** [comment]
> `g_balance_kill_delay 0` probably will be set to 0 in race too.

yep, please add it "0" by default in the Race.
