### ISSUE TITLE
Sorting servers by type does not work

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#25]
If you click "type":
![image](https://user-images.githubusercontent.com/68227075/226217112-c1c3af10-401b-4948-bd1d-c49ca33270fe.png)

It just adds a filter but it does not really sort like other columns (players, maps, etc.)

**Comment by kasymovga** [comment]
because it's actually filtering.

**Comment by YevheniiPokhvalii** [comment]
> because it's actually filtering.

strange behaviour. Other buttons actually sort the things.

**Comment by YevheniiPokhvalii** [comment]
I'd be useful to have the server type sorting as well.
