### ISSUE TITLE
Female and Male models have the same sounds

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#26]
If you choose a female character or a monster, all damage sounds will be robot defaults.
I tested in Nexuiz and there it works as expected - female, male, monsters, robots sound right.

**Comment by kasymovga** [comment]
i think you play with default forced model.
it's default for multiplayer. `seta g_player_forcemodel 0` must fix this.

**Comment by YevheniiPokhvalii** [comment]
> i think you play with default forced model. it's default for multiplayer. `seta g_player_forcemodel 0` must fix this.

Where is that setting in the GUI? Why is it so by default?

**Comment by kasymovga** [comment]
everything works fine for me. if you don't have "change model" option in esc menu then it's mean your model forced.
you always can check your current model with `chase_active 1`
note also that in some campaign modes player model also forced, but it will be probably "fixed", because it's actually needed only for faster game launch on android phones.
there is some complexity with gui option, but it will be added later.

**Comment by YevheniiPokhvalii** [comment]
> everything works fine for me. if you don't have "change model" option in esc menu then it's mean your model forced. you always can check your current model with `chase_active 1` note also that in some campaign modes player model also forced, but it will be probably "fixed", because it's actually needed only for faster game launch on android phones. there is some complexity with gui option, but it will be added later.

It started to work. I don't know why it did not work yesterday. I even restarted the game and it did not work.
Today, I tried it again and it seems to work file.

**Comment by YevheniiPokhvalii** [comment]
Again, some strange behaviour. I can change any model. I'm using `chase_active 1` to check it but right now when I choose Mulder or Nexus models, I got different models instead with monster sounds and no robotic sounds at all. Other models work fine.

**Comment by kasymovga** [comment]
it's because old nexuiz models is actually disabled.
game trying use closest model, but it's failed with nexus.zym (xolar and mulder), because new model called "rexus.dpm".
workaround will be added later.
