### ISSUE TITLE
Constantly display active weapon icon in HUD

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#27]
It is useful when the weapon model is hidden.
I mean something like that (to see it constantly on the HUD):
![image](https://user-images.githubusercontent.com/68227075/226220393-6e8e2c46-090d-4aac-b641-29310ce06214.png)

Maybe as an additional option "Always show active weapon icon".

**Comment by kasymovga** [comment]
esc -> game settings -> weapon bar fade speed -> stopped
