### ISSUE TITLE
[HUD] Ammo icons without color

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#28]
That's boring and not clearly indicated. Here is Nexuiz and Rexuiz comparison:

Rexuiz:
![image](https://user-images.githubusercontent.com/68227075/226221402-78cc9664-d35d-42a8-8b76-f968f6f6d1fa.png)

Nexuiz:
![image](https://user-images.githubusercontent.com/68227075/226221435-a8a18385-3388-4142-af0a-534a41ce7aad.png)

**Comment by kasymovga** [comment]
old icons available with simple items.
![rexuiz20230320121734-00](https://user-images.githubusercontent.com/9973821/226271848-491e93e5-8ca7-45d3-9c6c-2fb9bd6f6855.jpg)
settings -> game -> simple items
