### ISSUE TITLE
Add more options to customize simple items

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#29]
I'd nice to have a "simple items" customizable menu for combined solutions. For example, I don't like some of the simple items solutions like weapon look but I like lumina armour, ammo. Also, I don't want to change the HUD along with simple items or maybe just the opposite - I'd like to change the HUD to the one used with simple items without using simple items.

**Comment by kasymovga** [comment]
Just create your own pk3 then.

**Comment by YevheniiPokhvalii** [comment]
> Just create your own pk3 then.

Could you share an example?

**Comment by kasymovga** [comment]
pk3 is just zip archive.
zzz-rexdlc_simpleitems.pk3 contains simple items icons and items. copy it, remove models from copy, put copy to data folder (one level up from dlcache folder, local folder preferable but if it hard to find you can use game folder too).

**Comment by YevheniiPokhvalii** [comment]
> pk3 is just zip archive. zzz-rexdlc_simpleitems.pk3 contains simple items icons and items. copy it, remove models from copy, put copy to data folder (one level up from dlcache folder, local folder preferable but if it hard to find you can use game folder too).

Ok, got it. So no plans to add a more customizable simple items menu? Maybe in some far future?
