### ISSUE TITLE
Add assault game type

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#30]
This gametype already exists in Xonotic and can be ripped from there.

Xonotic team seems to abandon that gametype but it can actually be fun. The problem with Assault is mapping. This gametype requires some specific maps heavily based on a team work (team boosting, launching teammates as far as possible toward the map goals).

UT99 can be taken as a role model. They have the Assault League.
The official AL map list with the most played maps can be found there: https://www.utassault.net/
Downloads: https://unrealarchive.org/maps/unreal-tournament/assault/0/index.html

Check out their vids (you can see how complex assault maps can be finished in less than a minute using team work): 
https://www.youtube.com/watch?v=u1HDn8lFJ4I
https://www.youtube.com/watch?v=DZgjotWSvLM

In terms of Rexuiz, I see it as some sort of a race-cts mode, where one team prevents the other from accomplishing the map goals.

P.S. I am not sure but it seems there are no map converters to convert a UT99 map to Quake.

**Comment by kasymovga** [comment]
I removed this game type because it was
1. played by nobody
2. have very small amount of maps (actually there was only 1 map, which doesn't even included in Nexuiz-2.5.2)
If somebody will made some _original_ maps for this mode, then it will be have sense. In other case it's just waste of time.

**Comment by YevheniiPokhvalii** [comment]
> I removed this game type because it was
> 
> 1. played by nobody
> 2. have very small amount of maps (actually there was only 1 map, which doesn't even included in Nexuiz-2.5.2)
>    If somebody will made some _original_ maps for this mode, then it will be have sense. In other case it's just waste of time.

It could be just a showcase at the start of the game to least present that this gametype is there. Maybe after that would someone decide to do anything about it.
Since it does not exist nobody will even care.

**Comment by kasymovga** [comment]
from my experience with previously added game modes i can say with confidence:
even if it exist nobody will ever care.

**Comment by YevheniiPokhvalii** [comment]
> from my experience with previously added game modes i can say with confidence: even if it exist nobody will ever care.

People actually play coop and survival sometimes. Who knows if assault is played with interesting maps one day. 
I actually find it a big plus toward Rexuis that it is more versatile and got updates quicker than Xonotic.
That actually attracted my attention.

**Comment by kasymovga** [comment]
>coop and survival

These modes was added because there was a guy, who ported/made map for them.

>Why to remove something that is actually working?

Because it actually was not so "actually working".
