### ISSUE TITLE
Add a possibility to turn off autojump

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#32]
There is an option in Xonotic to turn off autojump. It can be kinda useful to test some stuff on trickjumping maps or when you have a jetpack.
Xonotic also has Jetpack on jump option, could be useful as well.

**Comment by kasymovga** [comment]
I have no idea how autojump can be related to jetpack. You need repress jump button in Rexuiz anyway to activate jetpack.
Anyway cl_nopogostick added.
