### ISSUE TITLE
map nexrun2_v1r3_fixed does not trigger a weapon

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#33]
I am not sure if it's a map bug or issues with the game. Full map name: `nexrun2_v1r3_fixed.pk3`
There is an error in console when you load this map offline: 

Loading waypoints failed
Unknown command `sv_hook_gamestart_race`

**Comment by kasymovga** [comment]
>Loading waypoints failed

Totally safe, race maps almost never provide waypoints (they are for bot navigation).

>sv_hook_gamestart_race

Fixed in master branch

**Comment by YevheniiPokhvalii** [comment]
> > Loading waypoints failed
> 
> Totally safe, race maps almost never provide waypoints (they are for bot navigation).
> 
> > sv_hook_gamestart_race
> 
> Fixed in master branch

Please check this map. Weapons do not show there. I mean I got the weapon but I cannot shoot. Also, there is another error in console:

```
Cvar_Set: variable _g_maplist not found
```

**Comment by kasymovga** [comment]
Rexuiz grenadelauncher need 4 rockets per shot in compare with 3 rockets in Nexuiz.

For this map you can use old weapon behavior with: `g_profile nexuiz25` (better put in in mapinfo as settemp) , note that this will affect some other weapons too.
Or you can modify this map so it will works correct way in Rexuiz.

**Comment by YevheniiPokhvalii** [comment]
> Rexuiz grenadelauncher need 4 rockets per shot in compare with 2 rockets in Nexuiz.
> 
> For this map you can use old weapon behavior with: `g_profile nexuiz25` (better put in in mapinfo as settemp) , note that this will affect some other weapons too. Or you can modify this map so it will works correct way in Rexuiz.

I see. Thank you for the details.

**Comment by kasymovga** [comment]
>and what is that error Cvar_Set: variable _g_maplist not found about?

nothing to worry about. i will fix it later.

**Comment by kasymovga** [comment]
Actually i think that race maps can be safely run in CTS mode. I will test it, if everything will work ok, i will unlock CTS mode for all Race maps.
