### ISSUE TITLE
[Race maps] Sometimes Kill command does not work correctly with checkpoints

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#34]
Steps to reproduce:
1. Try Race map `dibrun_fixed.pk3` or `hagarrun.pk3`
2. Enter the map
3. Do not move and type `kill` right just at the start of the map
4. You will be spawned at the next checkpoint.

Some addition: I think there should be 3 types of `kill` commands (Race map specific):
1. A command to `kill` you and bring you to the latest passed checkpoint
2. A `kill` command that brings you to the previous checkpoint (or probably you are able to indicate a previous checkpoint number. For example, `kill cp 2`  will bring you to the Checkpoint 2 if this checkpoint was already passed)
3.  A `kill` command that brings you right to the start of the map (something like `kill cp 0`). 

Right now the `kill` command will bring you to the latest passed checkpoint and if you type `kill` again, it will bring you to the previous checkpoint.

**Comment by YevheniiPokhvalii** [comment]
> it's intended behavior for not-qualifying stage of race. Use `g_race_qualifying_timelimit_override 20` to prevent this.

Could you explain what this command does?

**Comment by kasymovga** [comment]
race is 2 stage game mode: first is qualifying (which actually suppose to be some kind of warm up and also set players to different start positions), second is actual game play (at which players suppose to fight between each others).
first stage often misused as some kind of cts mode.
this variable enable qualifying.

**Comment by YevheniiPokhvalii** [comment]
> race is 2 stage game mode: first is qualifying (which actually suppose to be some kind of warm up and also set players to different start positions), second is actual game play (at which players suppose to fight between each others). first stage often misused as some kind of cts mode. this variable enable qualifying.

Oh, cool. Didn't expect that.
