### ISSUE TITLE
Texture and models errors in a single player demo map and survival

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#35]
![image](https://user-images.githubusercontent.com/68227075/228670946-8bcc0156-8768-46bf-b47a-514f97547e47.png)
![image](https://user-images.githubusercontent.com/68227075/228671240-a31f2575-00b6-419d-ba69-d965ab2d787c.png)

**Comment by kasymovga** [comment]
this is normal. pk3 not loaded at this stage.
