### ISSUE TITLE
Weapon bobbing option is missing

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#37]
Nexuiz had this option in the menu. You could turn the weapon bobbing off or even increase it.

**Comment by kasymovga** [comment]
nexuiz have view bobbing, not weapon bobbing. and this is awful setting for multiplayer. and it's not implemented in csqc movement prediction. and i am not going implement this anyway.

**Comment by YevheniiPokhvalii** [comment]
> nexuiz have view bobbing setting, not weapon bobbing. and this is awful setting for multiplayer. and it's not implemented in csqc movement prediction. and i am not going implement this anyway.

I see. But how to turn off the weapon bobbing.

**Comment by kasymovga** [comment]
`cl_bobmodel*`
i will add settings for this later.
