### ISSUE TITLE
Missing crosshair hit test and response on hit detection

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#38]
Quake 3 and Nexuiz have this feature. On top of that, Quake 3 has a dynamic crosshair that shows you hit detection by changing color, size when you shoot an enemy. 
![image](https://user-images.githubusercontent.com/68227075/228684396-03af8f8e-4bfb-402b-b5da-3db38b87d609.png)

**Comment by kasymovga** [comment]
quake 3 don't have this feature, it's have different feature that actually presents in rexuiz: `cvarlist crosshair_hit_*`
aim hit test in nexuiz is different thing and working pretty bad anyway (for example it's not working for grenade launcher).
and most of people don't understand this feature anyway (like you for example), so nobody really need it.

**Comment by YevheniiPokhvalii** [comment]
> 

I probably talked about Quake 3 OSP or CPM mods. I haven't played these for a long time already but I clearly remember I saw that somewhere.

**Comment by kasymovga** [comment]
```
crosshair_hit_time 0.2
crosshair_hit_size 4
cvarlist crosshair_hit_*
```
