### ISSUE TITLE
Weapon settings in the main menu and in the game do not match 

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#39]
Weapon left position does not work from the main menu.
Weapon hide is absent in the in-game menu.

**Comment by kasymovga** [comment]
it's working, you just need reconnect (restart in case of local game). Probably will fix apply button later for this.

>Weapon hide is absent in the in-game menu.
It's not supposed to copy everything from main menu.

**Comment by YevheniiPokhvalii** [comment]
> it's working, you just need reconnect (restart in case of local game). Probably will fix apply button later for this.
> 
> > Weapon hide is absent in the in-game menu.
> > It's not supposed to copy everything from main menu.

Please add hide weapon to this menu:

![image](https://user-images.githubusercontent.com/68227075/228970992-84c232ea-278e-422a-8c89-157cf78dfe3c.png)
