### ISSUE TITLE
Rexuiz not lauching after Commits on Jul 14, 2018

### ISSUE THREAD

**Issue by gustavozamboni** [kasymovga/rexuiz#4]
Hi, i'm using rexuizlauncher and after today's update i cant launch rexuiz anymore.

I'm on linux Mint, and here whats i get when i try to lanch the launcher:
(the screen blinks and nothing after)
~ $ rexuizlauncher 
juil. 14, 2018 9:14:22 PM com.rexuiz.Main main
INFOS: Application start
Game is Rexuiz using base gamedir data
gamename for server filtering: Nexuiz
Rexuiz Linux 07:18:07 Jul 14 2018 - release
Current nice level is below the soft limit - cannot use niceness
Skeletal animation uses SSE code path
Failed to init SDL joystick subsystem: 
execing quake.rc
execing default.cfg
execing defaultNexuiz.cfg
vid_bitsperpixel is read-only
execing physics26.cfg
execing ctfscoring-div0.cfg
execing balance.cfg
r_glsl is read-only
execing effects-normal.cfg
execing turrets.cfg
execing unit_machinegun.cfg
execing unit_hk.cfg
execing unit_hellion.cfg
execing unit_mlrs.cfg
execing unit_flac.cfg
execing unit_fusreac.cfg
execing unit_plasma.cfg
execing unit_plasma2.cfg
execing unit_tesla.cfg
execing unit_phaser.cfg
execing unit_walker.cfg
execing unit_ewheel.cfg
couldn't exec unit_repulsor.cfg
execing default25.cfg
execing physics25.cfg
execing balance25.cfg
execing rexuiz.cfg
execing rexuiz-extra.cfg
execing config.cfg
vid_bitsperpixel is read-only
couldn't exec data/campaign.cfg
execing config_update.cfg
couldn't exec autoexec.cfg
Client using an automatically assigned port
Client opened a socket on address 0.0.0.0:0
Client opened a socket on address [0:0:0:0:0:0:0:0]:0
Linked against SDL version 2.0.8
Using SDL library version 2.0.8
GL_VENDOR: Intel Open Source Technology Center
GL_RENDERER: Mesa DRI Intel(R) Haswell Desktop 
GL_VERSION: 3.0 Mesa 18.0.5
NOTE: requested 1x AA, got 0x AA
Video Mode: fullscreen 1920x1200x32x0.00hz
Draw_NewPic("gfx/vera-sans_cache_48_0_0_0_0_0_0_0"): frame 1: creating new cachepic
Draw_NewPic("gfx/vera-sans_cache_64_0_0_0_0_0_0_0"): frame 1: creating new cachepic
Draw_NewPic("gfx/vera-sans_cache_96_0_0_0_0_0_0_0"): frame 1: creating new cachepic

**Comment by kasymovga** [comment]
Will be fixed soon.

**Comment by kasymovga** [comment]
I think it fixed now.

**Comment by kasymovga** [comment]
Also, if you use old java launcher, you can try switch to new one: https://github.com/kasymovga/qrexuizlauncher/releases/

**Comment by gustavozamboni** [comment]
Thank, u very much, it is working now. I did also upgrade the java launcher. Thanks for the job, U R d 1
