### ISSUE TITLE
Add an option to ignore map info

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#41]
Some persistent maps like `piece-or-cake` don't allow to override their options. I remember that you mentioned that it's possible to unset those parameters but they might break something.
I'm not sure how it might be difficult to implement; however, it may be useful to have the option to ignore the map info in this menu:

![image](https://user-images.githubusercontent.com/68227075/228968933-8dc871d6-6fa4-40f7-94b0-142a36a0f07e.png)

**Comment by kasymovga** [comment]
`g_mapinfo_settemp_acl -*`

I will not add options which not needed for almost everybody.
