### ISSUE TITLE
Advanced server settings are not synced

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#42]
I can spectate but the settings says that it is not enabled. I think that's the same issue when two similar options are present in both menus in-game and server in-game menu.

![image](https://user-images.githubusercontent.com/68227075/228970030-51af1c11-64b3-40c4-ba7b-c3cbdb78acdb.png)

**Comment by kasymovga** [comment]
this option is just not exists anymore, i will delete it from gui later.
