### ISSUE TITLE
[Race] Server errors

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#43]
Similar issue but a different naming.

Unknown command `cl_hook_gamestart_rc`

![image](https://user-images.githubusercontent.com/68227075/228973211-a066d4d8-4a96-4cef-bbab-91fe4cb4c95f.png)

**Comment by kasymovga** [comment]
it's actually client error. and it's actually can be safely ignored.
i will fix this warning later.
