### ISSUE TITLE
[Race mode] Wrong weapon during spawn and bugs

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#44]
The common issue is that the weapon at the start should be a lazer instead of shotgun if you compare those maps in Nexuiz. But there are more differences. Here is the list of issues:

You start with a lazer in Nexuiz by default (without shotgun) and it's a shotgun in Rexuiz instead:
4d_nex_driving_stunts_v1r1
complexirace_v1r1_rc
cts_azure
cyberparcour01_v1r1_rc
cyberparcour02_v2_rc
cyberparcour03_v1r1_rc
HookRace_v1r1race_rc
ninja_run_1_rc
nordiccastle71race_r1_rc
ovalrace_b1r1_rc
powerslide_r2_rc
racetrack (default map)
runrunrun2_b1r1_rc
runrunrunrc4_rc
slalom_v1r1_rc
streetrace_v1r1_rc
test01_r2_rc
test99_v2r1_rc - this map can't even be passed wihout a starting lazer
yourewinner_v1r2_rc

You start with no weapon at all in Nexuiz by default and it is a shotgun in Rexuiz:
cel_hell_v1r4_rc
cel_hell_v2r1_rc
space_race_b2_rc
space_race_v2r1_rc
Usil-one_rc

You start with a lazer in Nexuiz but no weapon in Rexuiz:
test01_r2_rc

This map that does not work correctly in Rexuiz since you are supposed to spawn in a car with a lazer:
yourewinner_v1r2_rc

**Comment by kasymovga** [comment]
These maps must needed adapt to Rexuiz (if it's really needed), not vice versa.
