### ISSUE TITLE
Add god and give all, give ammo cheats

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#48]
Would be useful for testing, something like `impulse 99` and the `god` mode.
http://ouns.nexuizninjaz.com/tech_cheats.html
http://ouns.nexuizninjaz.com/tech_impulse.html

**Comment by kasymovga** [comment]
But `god` already working.
For unlimited weapon ammo you can use `prvm_edictset server 1 items 1`
