### ISSUE TITLE
Some Feature requests..

### ISSUE THREAD

**Issue by YoinkerBoinker** [kasymovga/rexuiz#5]
Hi, i read on the rexuiz itch.to page that it is okay to request some features here. So i thought about some requests which might be interesting to add.
First off all centered gun models would be nice to have, another thing are "simple items" because i  have a very had time actually seeing what weapon i pick up because they either look somewhat similar or it's just to dark (even at fullbright) to tell. 
Speaking about that it also would be nice to show where a certain weapon is on the map when pressing the key for it (like it is already implemented in xonotic). This would help a lot of new players to actually enjoy maps they don't know.

**Comment by kasymovga** [comment]
>First off all centered gun models would be nice to have
This actually already done, but not available with default settings. Center position available with g_shootfromeye 1 for example. I will add option for force center position.
> Speaking about that it also would be nice to show where a certain weapon is on the map when pressing the key for it
This is server side option (g_showweaponspawns). I will add some cl_showweaponspawns so it will depend only of client settings.
>simple items
This one tricky. I think i will add it, but later than other features.

Note that all changes will work only on servers with latest version. I think only "Best" servers have regular updates.

**Comment by kasymovga** [comment]
Currently simple items can be achieved with this custom pack:
http://rexuiz.trafflow.com/maps/z-simpleitems-test.pk3
It must be placed in data folder. Will be work with most of servers.
This pack is ugly, but working.
I will add feature to client to activating/deactivating simple items later.

Other features implemented. They available in "game settings" in in-game menu. Will work only on servers with latest updates.

**Comment by YoinkerBoinker** [comment]
Hey thank you for your response. Good to hear that most of the features are already in the game. I'll look into it. Thanks again!

**Comment by YoinkerBoinker** [comment]
I don't wanna open another issue on that because its basically not an issue.
I just want to metion that when you play offline different gun-positions are always ignored on your first spawn (means you will always spawn "right-handed"). To "fix" it you just have to switch weapons or die. After that you will always spawn with the "correct" gun position.

**Comment by kasymovga** [comment]
Thank you for feedback. Will fix it on next release.

**Comment by YoinkerBoinker** [comment]
No Problem. It actually only seem to happen in Arena Campaign. But it's not that big of a deal. But that's basically it. No more complains so far. Thank you for this great game it's a lot of fun.
