### ISSUE TITLE
Looking to rent a Rexuiz server?

### ISSUE THREAD

**Issue by citadelservers** [kasymovga/rexuiz#6]
Hi everyone, we're a hosting company and support Rexuiz, you can rent a Rexuiz game server from us and help the community grow for an awesome game like this: https://citadelservers.com/en-gb/game-servers/rexuiz-game-hosting

**Comment by kasymovga** [comment]
Thank you for information. But this is not a place for promotion.

**Comment by citadelservers** [comment]
@kasymovga Is there any way we can directly contact you? We'd like to discuss becoming an official hosting partner with you, it can greatly benefit your game to have a worldwide host such as us to help support your game/
