### ISSUE TITLE
unable to make

### ISSUE THREAD

**Issue by akami-channel** [kasymovga/rexuiz#7]
I was trying to use make, and ran into a lot of messages like this:

/usr/bin/ld: /home/akami/s/code/repos/rexuiz/libs/linux64//lib/libSDL2.a(SDL_dropevents.o):(.bss+0x38): multiple definition of `WAYLAND_wl_proxy_get_user_data'; /home/akami/s/code/repos/rexuiz/libs/linux64//lib/libSDL2.a(SDL_events.o):(.bss+0x38): first defined here

Followed by these errors:
collect2: error: ld returned 1 exit status
make[3]: *** [makefile.inc:543: rexuiz-sdl] Error 1
make[3]: Leaving directory '/home/akami/s/code/repos/rexuiz/DarkPlacesRM/build-obj/release/rexuiz-sdl'
make[2]: *** [makefile.inc:445: bin-release] Error 2
make[2]: Leaving directory '/home/akami/s/code/repos/rexuiz/DarkPlacesRM'
make[1]: *** [makefile.inc:388: sdl-rexuiz] Error 2
make[1]: Leaving directory '/home/akami/s/code/repos/rexuiz/DarkPlacesRM'
make: *** [Makefile:278: engine] Error 2

It looks to me like I may be experiencing a similar problem to what is talked about in this issue:

https://github.com/polybar/polybar/issues/2097

I am using Arch, but I don't think that's directly related. Are you using GCC 10 or GCC 9?

**Comment by kasymovga** [comment]
I use gcc 9.3 and gcc 4.4.
For gcc 10 you can try add pass extra flag for linker:
`make CC=gcc -Wl,--allow-multiple-definition `
Here you can read explanation: https://medium.com/@clentfort/using-esy-sdl2-with-gcc-10-91b4fa0c5aa9
Anyway there is no reason build game from this sources. You can just download ready binaries: http://rexuiz.com/files

**Comment by kasymovga** [comment]
Must be fixed in current version of SDL2.
